### PR TITLE
Week 2 Task 1 - Mansi

### PR DESCRIPTION
**Pull request by Mannxxx**
Issue: #303 

Shared the doc file with iit2022255@iiita.ac.in

### CODE REVIEW

**Comment by rakim-0** [comment]
We require the flags from the file hyperlinked in the issue

**Comment by Mannxxx** [comment]
Could you reshare the link? I wasn't able to access it.

**Comment by rakim-0** [comment]
https://cdn.discordapp.com/attachments/837657086904631388/1187308836340650004/file

**Comment by rakim-0** [comment]
Yep sure I'll just upload the file here 
[file.zip](https://github.com/opencodeiiita/CyberRepo-2077/files/13769834/file.zip)

**Comment by rakim-0** [comment]
Any updates?

**Comment by rakim-0** [comment]
Closed since the deadline is over and there was no response.

**Pull request closed without merging**
