### PR TITLE
Complete Task 3

### PR DESCRIPTION
**Pull request by criticic**
Issue: #3

Make sure to add all the required items as per each issue.

### CODE REVIEW

**Comment by rakim-0** [comment]
We require the contents of each folder in the PATH environment variable. I.E

**Comment by rakim-0** [comment]
We require the list of files in all the folders in the PATH environment variable not the value of PATH itself.

**Review by rakim-0 — CHANGES_REQUESTED** [review]
We require the list of files in all the folders in the PATH environment variable not the value of PATH itself.
That is the output for ls for each folder. There's a BASH one liner for the same.

**Comment by criticic** [comment]
@rakim-0 I have updated the PR, kindly take a look

**Review by rakim-0 — APPROVED** [review]

**Pull request merged**
