### PR TITLE
Week3-task1

### PR DESCRIPTION
**Pull request by Aswinr24**
Issue: #345

Added the drive link having the solution and the screenshot to the txt file

### CODE REVIEW

**Comment by rakim-0** [comment]
Can you create a new PR, I had forgotten to remove myself from the issue assignment so maybe that's causing the issue.

Also please add information on how you got the flag too. Either the code or the steps suffice.

**Comment by Aswinr24** [comment]
Done, Added the code to get the solution in the docs file

**Comment by Aswinr24** [comment]
Shall I make a new Pull Request?

**Comment by rakim-0** [comment]
Well done! Points will be manually given to you by today afternoon.

**Pull request merged**
