### PR TITLE
Task2 completed

### PR DESCRIPTION
**Pull request by ajay484**
Issue: #2

### CODE REVIEW

**Comment by rakim-0** [comment]
It's two different tasks.
1. One command should for accessing super user, i.e logging in as the super user/root user.
2. The second one is modifying a file permission to make it an executable.

**Comment by ajay484** [comment]
@rakim-0  i have updated the files please check

**Comment by rakim-0** [comment]
It's still incorrect. I think you're misunderstanding. sudo only gives the executable higher privileges.

**Comment by ajay484** [comment]
@rakim-0 i have made the changes please checkit

**Pull request merged**
