### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by shorty-huddybuddy**
Issue: #2

### CODE REVIEW

**Comment by rakim-0** [comment]
What about the command to access super user?

**Comment by shorty-huddybuddy** [comment]
it is sudo only right ! it is in the command ,file name tesk-2.txt

**Comment by rakim-0** [comment]
No sudo itself doesn't give you the access to becoming the super user/root user

**Comment by shorty-huddybuddy** [comment]
yeah .
i have done changes ,please cheack

**Pull request merged**
