### PR TITLE
Task 3: Execute a BASH command to print the contents of the environment variable PATH

### PR DESCRIPTION
**Pull request by Sandipan3**
Issue: #3 

Execute a BASH command to print the contents of the environment variable PATH

Screenshot 2023-12-17 184350
[command.txt](https://github.com/opencodeiiita/CyberRepo-2077/files/13696221/command.txt)

### CODE REVIEW

**Comment by rakim-0** [comment]
We want the contents of the folder in the path variable, not the value of  path itself which is trivial.
You're almost there, just figure out a way to connect the folder list output and ls.

**Comment by Sandipan3** [comment]
ls $(echo $PATH | tr ":"   " ")

Will this command do the required job?

**Comment by rakim-0** [comment]
Yep that's one way to do it. Add to the file and I'll merge it.

**Comment by Sandipan3** [comment]
Thanks for your help.

**Pull request closed without merging**
