### PR TITLE
added task1

### PR DESCRIPTION
**Pull request by akoolarni**
Issue: #1 

I have added the screenshot of the kali linux after downloading.
Please merge the PR

### CODE REVIEW

**Comment by akoolarni** [comment]
@DRedDevil04 @opencode-bot 
Please merge my PR.

**Comment by rakim-0** [comment]
Your screenshot doesn't include date. Either include it via running date on terminal or whatever way you wish

**Comment by rakim-0** [comment]
Since there has been no update for quite some time, I'll be closing the PR.

**Comment by akoolarni** [comment]
Sorry to say but some maintainers in this contest are not behaving properly, which I personally experienced. 
So I opt out of this contest.
I don't care now

**Pull request closed without merging**
