### PR TITLE
Task 1

### PR DESCRIPTION
**Pull request by rnavaneeth992**
Issue: #1 

Make sure to add all the required items as per each issue.

Submission\rnavaneeth992\week1\task1

Added My Screenshot of Kali Linux

### CODE REVIEW

**Comment by rakim-0** [comment]
Timestamp with date not included.

**Comment by rnavaneeth992** [comment]
Ok I will include it

**Comment by rakim-0** [comment]
Yes I can see that why I explicitly mentioned Date. I can't see any date either on the host nor on your VM

**Comment by rnavaneeth992** [comment]
> Yes I can see that why I explicitly mentioned "**date**". I can't see any date either on the host nor on your VM

Oh ok Next time onwards I will add , can you add merge PR 
Or should I change and push

**Comment by rakim-0** [comment]
Change and push

**Comment by rnavaneeth992** [comment]
Ok Sure

**Comment by rnavaneeth992** [comment]
Can you check now @rakim-0

**Pull request merged**
