### PR TITLE
Week 2 Task 3

### PR DESCRIPTION
**Pull request by Apoorv012**
Issue: #306

### CODE REVIEW

**Comment by DRedDevil04** [comment]
@Apoorv012 please undo task 4 commit from this PR....make a different PR for that

**Comment by Apoorv012** [comment]
@DRedDevil04 I have undo the changes

**Comment by DRedDevil04** [comment]
@Apoorv012 also, in task three, specify what exactly will happen when you overwrite the bytes wrt the given program

**Comment by Apoorv012** [comment]
@DRedDevil04 I have made the required changes

**Pull request merged**
