### PR TITLE
Task 2: Run command to access super user mode and give executable permission to any file.

### PR DESCRIPTION
**Pull request by Sandipan3**
Issue: #2 

Run command to access super user mode and give executable permission to any file is done.
[helloWorld.txt](https://github.com/opencodeiiita/CyberRepo-2077/files/13685665/helloWorld.txt)
Screenshot 2023-12-15 184925

### CODE REVIEW

**Comment by rakim-0** [comment]
What about the command to access super user mode?

**Comment by rakim-0** [comment]
No those two were independent questions. Your answer to executable permission is fine. But how would you access the super user mode as a user?

**Comment by Sandipan3** [comment]
I apologize for my mistake. I forgot to add "su" after "sudo" for running in super user mode. Please correct me if I am wrong.

**Comment by rakim-0** [comment]
Yep that's it add it to the file and I'll merge it.

**Comment by Sandipan3** [comment]
Thanks ffor your feedback.

**Pull request closed without merging**
